version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: luxury-ecommerce-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: luxury-ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: luxury-ecommerce-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/luxury-ecommerce?authSource=admin
      JWT_ACCESS_SECRET: your_super_secret_access_token_key_change_in_production
      JWT_REFRESH_SECRET: your_super_secret_refresh_token_key_change_in_production
      CLIENT_URL: http://localhost:5173
      # Add your other env variables here
    depends_on:
      - mongodb
    networks:
      - ecommerce-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: luxury-ecommerce-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecommerce-network

volumes:
  mongodb_data:

networks:
  ecommerce-network:
    driver: bridge

